name: Build and Test Workflow

on:
  push:
    branches:
      - '*'

permissions:
  contents: read

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repo
        uses: actions/checkout@main
    
      - name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: pip install pylint && pylint ./bb-ripper/
      - run: python3 ./bb-ripper/.
        env:
          BB_USER : ${{ secrets.BB_USER }}
          BB_WORKSPACE: ${{ secrets.BB_WORKSPACE }}
          BB_PASSWORD: ${{ secrets.BB_PASSWORD }}
          BB_RIPPER_EXPORT_DIRECTORY: ${{ secrets.BB_RIPPER_EXPORT_DIRECTORY }}
  