name: Test Docker Image Workflow

on:
  push:
    branches:
      - '122-docker-image-*'

jobs:

  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Echo run id
        run: echo ${{ github.run_id }}

      - name: Check out repo
        uses: actions/checkout@v4

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/jvrck/bbripper:${{ github.run_id }}

      - name: Build and push Docker with AWS
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          build-args: AWSCLI=TRUE
          push: true
          tags: |
            ghcr.io/jvrck/bbripper:${{ github.run_id }}-aws

  purge-image:
    name: Delete image from ghcr.io
    runs-on: ubuntu-latest
    needs: build-and-push-images
    if: always()
    steps:
      - name: Delete image
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          # NOTE: at now only orgs is supported
          owner: jvrck
          name: bb-ripper
          # NOTE: using Personal Access Token
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.run_id }}