name: Test Docker Image Workflow

on:
  push:
    branches:
      - '122-docker-image-*'

jobs:

  build-and-run-images:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        
      - name: Build and Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          push: false
          tags: |
            ghcr.io/jvrck/bbripper:${{ github.run_id }}

      - name: Run Docker image
        run: |
          docker run \
            -e BB_USER=$BB_USER \
            -e BB_WORKSPACE=$BB_WORKSPACE \
            -e BB_PASSWORD=$BB_PASSWORD \
            ghcr.io/jvrck/bbripper:${{ github.run_id }}
        env:
          BB_USER: ${{ secrets.BB_USER }}
          BB_WORKSPACE: ${{ secrets.BB_WORKSPACE }}
          BB_PASSWORD: ${{ secrets.BB_PASSWORD }}

      # - name: Build and push Docker with AWS
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     platforms: linux/amd64
      #     file: ./Dockerfile
      #     build-args: AWSCLI=TRUE
      #     push: false
      #     tags: |
      #       ghcr.io/jvrck/bbripper:${{ github.run_id }}-aws

  # Run-image:
  #   name: Run built image
  #   runs-on: ubuntu-latest
  #   needs: build-and-push-images
  #   if: success()
  #   steps:
  #     - name: Echo run id
  #       run: echo ${{ github.run_id }}
