name: Test Docker Image Workflow

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'release-*'

jobs:
  build-and-run-images:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        
      - name: Build and Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          push: false
          tags: |
            ghcr.io/jvrck/bbripper:${{ github.run_id }}

      - name: Run Docker image
        run: |
          docker run \
            -e BB_USER=$BB_USER \
            -e BB_WORKSPACE=$BB_WORKSPACE \
            -e BB_PASSWORD=$BB_PASSWORD \
            ghcr.io/jvrck/bbripper:${{ github.run_id }}
        env:
          BB_USER: ${{ secrets.BB_USER }}
          BB_WORKSPACE: ${{ secrets.BB_WORKSPACE }}
          BB_PASSWORD: ${{ secrets.BB_PASSWORD }}

  build-and-run-aws-images:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        
      - name: Build and Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          build-args: AWSCLI=TRUE
          push: false
          tags: |
            ghcr.io/jvrck/bbripper:${{ github.run_id }}-aws

      - name: Run Docker image
        run: |
          docker run \
            -e BB_USER=$BB_USER \
            -e BB_WORKSPACE=$BB_WORKSPACE \
            -e BB_PASSWORD=$BB_PASSWORD \
            ghcr.io/jvrck/bbripper:${{ github.run_id }}-aws
        env:
          BB_USER: ${{ secrets.BB_USER }}
          BB_WORKSPACE: ${{ secrets.BB_WORKSPACE }}
          BB_PASSWORD: ${{ secrets.BB_PASSWORD }}

      - name: Run Docker image - Check AWS CLI
        run: |
          docker run \
            ghcr.io/jvrck/bbripper:${{ github.run_id }}-aws aws --version
        env:
          BB_USER: ${{ secrets.BB_USER }}
          BB_WORKSPACE: ${{ secrets.BB_WORKSPACE }}
          BB_PASSWORD: ${{ secrets.BB_PASSWORD }}
