name: Push Image Workflow

on:
  push:
    tags:
      - '*'
    branches:
      - 150-weekly-builds

jobs:

  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
    
      - name: Login to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github Packages
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build and push Docker image
        uses: docker/build-push-action@master
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          push: false
          tags: |
            jvrck/bbripper:latest
            jvrck/bbripper:${{ github.ref_name }}
            ghcr.io/jvrck/bbripper:latest
            ghcr.io/jvrck/bbripper:${{ github.ref_name }}

  build-and-push-awscli-images:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
    
      - name: Login to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github Packages
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker with AWS
        uses: docker/build-push-action@master
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          build-args: AWSCLI=TRUE
          push: false
          tags: |
            jvrck/bbripper:latest-aws
            jvrck/bbripper:${{ github.ref_name }}-aws
            ghcr.io/jvrck/bbripper:latest-aws
            ghcr.io/jvrck/bbripper:${{ github.ref_name }}-aws
